# =========================================================================
#   Motor Control Project - Ceedling Configuration
#   TDD-focused embedded motor control development
# =========================================================================

---
:project:
  :which_ceedling: gem
  :ceedling_version: 1.0.1

  # Enable mocks for hardware abstraction layer testing
  :use_mocks: TRUE
  :use_test_preprocessor: :none
  :use_deep_preprocessor: :none
  :use_backtrace: :simple
  :use_decorators: :auto

  :build_root: build
  :test_file_prefix: test_
  :default_tasks:
    - test:all

  # Optimize for fast iteration during TDD
  :test_threads: 8
  :compile_threads: 8

  :release_build: FALSE

:mixins:
  :enabled: []
  :load_paths: []

:test_build:
  :use_assembly: FALSE

:release_build:
  :output: motor_control.out
  :use_assembly: FALSE
  :artifacts: []

# Essential plugins for motor control development
:plugins:
  :load_paths: []
  :enabled:
    - module_generator                # Quick creation of source/header/test templates
    - report_tests_pretty_stdout      # Clean, readable test output
    #- gcov                           # Uncomment when you want code coverage reports

:extension:
  :executable: .out
  :header: .h
  :source: .c

# Directory structure for motor control project
:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
    - src/motor_control/**
    - src/hal/**
    - src/drivers/**
  :include:
    - src/**
    - src/motor_control/**
    - src/hal/**
    - src/drivers/**
  :support:
    - test/support
  :libraries: []

:files:
  :test: []
  :source: []

# Compilation defines for embedded/motor control
:defines:
  :test:
    - TEST
    - UNIT_TEST
    - ARM_MATH_CM4        # Enable ARM DSP library math functions
    - USE_HAL_DRIVER      # For STM32 HAL compatibility in abstractions
  :release:
    - ARM_MATH_CM4
    - USE_HAL_DRIVER
    - STM32F4            # Update to your specific MCU

  :use_test_definition: FALSE

# Compiler flags optimized for embedded C development
:flags:
  :test:
    :compile:
      :*:
        - -std=c99              # C99 standard (good balance for embedded)
        - -Wall                 # All warnings
        - -Wextra               # Extra warnings
        - -Werror               # Treat warnings as errors (enforce quality)
        - -Wno-unused-parameter # Allow unused params in HAL interfaces
        - -Wno-missing-field-initializers
        - -pedantic             # Strict ISO C
        - -ffunction-sections   # Optimize for embedded (even in tests)
        - -fdata-sections
        - -O0                   # No optimization for debugging tests
        - -g3                   # Maximum debug info
        # Math optimizations for motor control algorithms
        - -ffast-math           # Faster floating point (acceptable for motor control)
        - -fsingle-precision-constant

# CMock configuration for hardware abstraction mocking
:cmock:
  :plugins:
    - :ignore              # Allow ignoring function calls
    - :callback            # Enable callbacks for complex mocking
    - :return_thru_ptr     # Handle pointer return values
  
  :verbosity: 2
  :when_no_prototypes: :warn

  :mock_prefix: 'mock_'
  :mock_suffix: ''

  # Handle embedded C attributes
  :strippables:
    - '(?:__attribute__\s*\([ (]*.*?[ )]*\)+)'
    - '(?:__packed)'
    - '(?:__weak)'
    - '(?:__interrupt)'
  
  :attributes:
    - __ramfunc
    - __irq
    - __fiq
    - __interrupt
    - __weak
    - __packed
    - register
    - extern
    - volatile
    - inline
    - static
  
  :c_calling_conventions:
    - __stdcall
    - __cdecl
    - __fastcall

  :treat_externs: :exclude
  :treat_inlines: :exclude

  # Type handling for embedded types
  :treat_as:
    uint8_t:    HEX8
    uint16_t:   HEX16
    uint32_t:   HEX32
    int8_t:     INT8
    int16_t:    INT16
    int32_t:    INT32
    bool:       UINT8
    size_t:     UINT32
  
  :memcmp_if_unknown: true
  :when_ptr: :compare_data

  # Mock behavior for safety-critical motor control
  :enforce_strict_ordering: FALSE    # Allow flexible test setup
  :fail_on_unexpected_calls: TRUE    # Catch missing expectations
  :callback_include_count: true
  :callback_after_arg_check: false
  
  :exclude_setjmp_h: false

# Unity configuration for floating-point motor control math
:unity:
  :defines:
    # EXCLUDE float if you want faster tests, but motor control needs it!
    # - UNITY_EXCLUDE_FLOAT
    - UNITY_FLOAT_PRECISION=0.0001f   # Precision for motor control comparisons
    - UNITY_INCLUDE_DOUBLE            # Support double precision calculations

:environment: []

# Libraries for motor control (ARM CMSIS-DSP could be added here)
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system:
    - m  # Math library (required for motor control algorithms)
  :test: []
  :release: []

################################################################
# CODE COVERAGE (Uncomment gcov plugin above to use)
################################################################

:gcov:
  :summaries: TRUE
  :report_task: TRUE
  :utilities:
    - gcovr
  :reports:
    - HtmlDetailed  # Detailed HTML report for identifying untested code
    - Text          # Quick summary in terminal
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90
    # Coverage goals for safety-critical motor control:
    # - Motor control algorithms: 100%
    # - HAL abstractions: 100%
    # - Drivers: 80%+ (hardware-dependent code harder to test)

################################################################
# MODULE GENERATOR SETTINGS
################################################################

:module_generator:
  :naming: :snake  # Use snake_case (pid_controller, not PidController)
  :includes:
    :tst:
      - unity.h
      - mock_*.h  # Auto-include mocks
    :src:
      - stdint.h
      - stdbool.h
  :boilerplates:
    :src: |
      /**
       * @file %{module_name}.c
       * @brief %{module_name} implementation
       * 
       * Motor control component - tested via TDD
       */
      
      #include "%{module_name}.h"
      
    :inc: |
      /**
       * @file %{module_name}.h
       * @brief %{module_name} interface
       * 
       * Motor control component - tested via TDD
       */
      
      #ifndef %{module_name_upper}_H
      #define %{module_name_upper}_H
      
      #include <stdint.h>
      #include <stdbool.h>
      
      
      
      #endif // %{module_name_upper}_H
    :tst: |
      /**
       * @file test_%{module_name}.c
       * @brief Unit tests for %{module_name}
       */
      
      #include "unity.h"
      #include "%{module_name}.h"
      
      void setUp(void) {
          // Runs before each test
      }
      
      void tearDown(void) {
          // Runs after each test
      }
      
      void test_%{module_name}_NeedToImplement(void) {
          TEST_IGNORE_MESSAGE("Need to implement %{module_name}");
      }

################################################################
# TOOLCHAIN (Currently using native GCC for testing)
################################################################

# Leave :tools blank to use Ceedling's default GCC configuration
# This works perfectly for testing motor control algorithms on your dev machine
# When you need ARM cross-compilation for hardware, we'll configure it then
:tools:
# Ceedling defaults to gcc - which is what we want for host-based unit tests

################################################################
# BEST PRACTICES NOTES
################################################################

# TDD WORKFLOW:
# 1. Write test first:       ceedling test:test_pid
# 2. Watch it fail (RED):    Expected behavior
# 3. Implement minimum code: Make it pass
# 4. Watch it pass (GREEN):  Verify correctness
# 5. Refactor if needed:     Improve while staying green
# 6. Repeat:                 Next feature/test
#
# MOTOR CONTROL TESTING STRATEGY:
# - Unit test ALL algorithms: PID, FOC, Clarke/Park transforms
# - Mock ALL hardware: ADC, PWM, Timers, GPIO
# - Test edge cases: Saturation, overflow, zero-crossing
# - Test safety: Overcurrent, overvoltage, runaway protection
# - Integration tests: Later, on hardware
#
# USEFUL COMMANDS:
# ceedling test:all              - Run all tests
# ceedling test:test_pid         - Run specific test file
# ceedling test:pid              - Run tests for pid module
# ceedling gcov:all              - Generate coverage report
# ceedling module:create[pid]    - Create new module with test
# ceedling clean                 - Clean build artifacts
# ceedling summary               - Show test summary
#
# FILE ORGANIZATION:
# src/motor_control/    - Motor control algorithms (FOC, PID, transforms)
# src/hal/              - Hardware abstraction interfaces
# src/drivers/          - Low-level hardware drivers (will mock in tests)
# test/                 - All unit tests
# test/support/         - Test helpers and utilities

...